worker_processes auto;
pid /tmp/chatbox/nginx/nginx.pid;
error_log stderr;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log off;
    sendfile on;

    client_body_temp_path /tmp/chatbox/nginx/client-body;
    proxy_temp_path /tmp/chatbox/nginx/proxy;

    include /tmp/chatbox/nginx/conf.d/*.conf;
}
