# /etc/zsh/zshenv: system-wide .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# 工具链 env 与 PATH 由 profile.d 统一维护，POSIX sh 语法在 zsh 下同样可用。
. /etc/profile.d/app.sh

if [ -d /etc/zshenv.d ]; then
  for i in /etc/zshenv.d/*.zsh; do
    if [ -r "$i" ]; then
      source "$i"
    fi
  done
  unset i
fi
