[containers]
log_driver = "k8s-file"
log_size_max = 10485760
cgroups = "disabled"
apparmor_profile = "unconfined"
label = false
http_proxy = false

[network]
network_backend = "netavark"
firewall_driver = "nftables"
dns_bind_port = 53
default_rootless_network_cmd = "pasta"

[engine]
cgroup_manager = "cgroupfs"
database_backend = "sqlite"
events_logger = "file"
hooks_dir = []
service_timeout = 0
runtime = "crun"
helper_binaries_dir = ["$BINDIR/../libexec/podman"]

[engine.runtimes]
crun = []
