[empty]
type = memory

[workspace]
type = union
upstreams = /workspace:ro empty::ro

[logs]
type = union
upstreams = /var/log:ro empty::ro

[files]
type = combine
upstreams = workspace=workspace: logs=logs: upload=/upload
