[storage]
driver = "vfs"
transient_store = false
graphroot = "/opt/podman/data/graphroot"
runroot = "/run/user/5230/podman/storage"

[storage.options.pull_options]
enable_partial_images = "true"
use_hard_links = "false"
