name: Publish workspace images

on:
  push:
    paths:
      - '.github/workflows/publish-workspace-images.yaml'
      - 'platform/container/workspace/**'
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      disable_docker_cache:
        description: Disable Docker cache
        default: false
        required: false
        type: boolean

jobs:
  build:
    name: build (${{ matrix.image.tag }})
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - base: 'debian:10'
            tag: 'debian10'
          # - base: 'debian:12'
          #   tag: 'debian12'
          - base: 'debian:13'
            tag: 'debian13'
          - base: 'ubuntu:26.04'
            tag: 'ubuntu26.04'
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v4
        with:
          driver-opts: network=host
          buildkitd-flags: >-
            --allow-insecure-entitlement network.host
            --allow-insecure-entitlement security.insecure
            --oci-worker-net=host

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v7
        with:
          context: .
          file: platform/container/workspace/Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64
          network: host
          cache-from: type=registry,ref=ghcr.io/curoky/codespace-cache:workspace-${{ matrix.image.tag }}-amd64
          cache-to: type=registry,ref=ghcr.io/curoky/codespace-cache:workspace-${{ matrix.image.tag }}-amd64,mode=max,oci-mediatypes=true,compression=zstd,compression-level=3
          no-cache: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.disable_docker_cache == true) }}
          build-args: BASE_IMAGE=${{ matrix.image.base }}
          tags: ghcr.io/curoky/codespace:workspace-${{ matrix.image.tag }}
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3
